#!/bin/bash
set -ex

echo "Running tests..."

export BASE_IMAGE=${1:-"ubuntu/jre:21_test"}
export BUILD_IMAGE=${2:-"ubuntu/jre:test-builder-20"}
export M2_CACHE=${3:-"/home/pushkarnk/work/.m2"}
export MAVEN_IMAGE=${4:-"ubuntu/jre:test-maven-21"}

compile() {
	javac -source 17 -target 17 $1 $2
}

run_container() {
	docker run --rm -v $PWD:/app:ro -w /app $3 $1 $2
}

export -f compile
export -f run_container

mkdir -p ${M2_CACHE}

CURRENT_DIR="$(dirname $(readlink -f $0))"

for test_dir in "$CURRENT_DIR"/*/
do
    if [[ -x ${test_dir}/runtest ]]; then

        pushd $test_dir

        ./runtest

        popd
    fi
done
