ARG BASE_IMAGE=ubuntu/jre:21_test
ARG MAVEN_IMAGE=maven:3.9.4-eclipse-temurin-17
ARG JDK21_IMAGE=maven:3-amazoncorretto-21-al2023
FROM $MAVEN_IMAGE as builder
FROM $JDK21_IMAGE as jdk21

FROM $BASE_IMAGE

COPY --from=builder /bin/sh /bin/sh
COPY --from=builder /usr/bin/chmod /usr/bin/chmod
COPY --from=builder /usr/bin/uname /usr/bin/uname
COPY --from=builder /usr/bin/dirname /usr/bin/dirname
# note, Temurin base does not install into /etc/maven and /usr/share/java
# other base might require copying those folders
COPY --from=builder /usr/share/maven /usr/share/maven

ENV JAVA_HOME=/opt/java

# Add javac compiler for maven (it always recompiles package-info.java)

COPY --from=jdk21 /lib/jvm/java-21/bin/javac \
    /opt/java/bin/
# compatibility signatures
COPY --from=jdk21 /lib/jvm/java-21/lib/ct.sym \
    /opt/java/lib/
# additional jars
COPY --from=jdk21 /lib/jvm/java-21/lib/jrt-fs.jar \
    /opt/java/lib/

# copy modules
COPY --from=jdk21 /lib/jvm/java-21/lib/modules \
    /opt/java/lib/

ENTRYPOINT [ "/usr/share/maven/bin/mvn" ]
